"""``ruddy model`` — explicit inferential models over a dataset."""

from __future__ import annotations

import typer

from ruddy.cli._enums import (
    Alignment,
    BootstrapMethod,
    CorrelationMethod,
    PAdjust,
    RobustCovariance,
    SSType,
)
from ruddy.cli._options import (
    ANNOTATION,
    BOOTSTRAP_METHOD,
    BOOTSTRAP_RESAMPLES,
    CATEGORICAL,
    CONDITION_NUMBER_THRESHOLD,
    CONFIDENCE_LEVEL,
    CONTEXT_SETTINGS,
    COVARIATE,
    DEPENDENCE_MAX_COLUMNS,
    DEPENDENCE_MIN_PAIRS,
    DEPENDENCE_PERMUTATIONS,
    DIAGNOSTIC_ALPHA,
    EXCLUDE,
    FACTOR,
    FEATURE_ALIGNMENT,
    FEATURE_COLUMN,
    FEATURE_ID_COLUMN,
    FEATURE_IDS_FILE,
    FEATURE_INPUT,
    FORMULA,
    GROUP,
    ID_COLUMN,
    INTERACTION,
    INTERVAL_CORRELATION,
    MARGINAL_COVARIATE,
    MARGINAL_FACTOR,
    MARGINAL_FORMULA,
    MARGINAL_INTERACTION,
    MARGINAL_P_ADJUST,
    MARGINAL_RESPONSE,
    MARGINAL_TERM,
    MAX_CATEGORY_LEVELS,
    MAX_DESIGN_CELLS,
    MAX_DESIGN_COLUMNS,
    MAX_FACTOR_LEVELS,
    MAX_INTERACTION_ORDER,
    MAX_MISSINGNESS_PATTERNS,
    MAX_PAIRWISE_COLUMNS,
    MAX_RESPONSES,
    MAX_SHAPIRO_N,
    MI_NEIGHBORS,
    MIN_CELL_N,
    MIN_LEVEL_N,
    MIN_NUMERIC_N,
    MIXED_COVARIATE,
    MIXED_FACTOR,
    MIXED_FORMULA,
    MIXED_GROUP_REQUIRED,
    MIXED_INTERACTION,
    MIXED_MAX_ITER,
    MIXED_MIN_GROUP_N,
    MIXED_MIN_GROUPS,
    MIXED_ML,
    MIXED_OPTIMIZER,
    MIXED_RANDOM_SLOPE,
    MIXED_RESPONSE,
    NUMERIC,
    OUTPUT_DIR,
    P_ADJUST_NONE,
    PARTIAL_COVARIATE,
    PERMANOVA_FACTOR,
    PERMANOVA_MAX_GROUP_LEVELS,
    PERMANOVA_METRIC,
    PERMANOVA_MIN_GROUP_N,
    PERMANOVA_PERMUTATIONS,
    RANDOM_STATE,
    RESPONSE,
    ROBUST_COVARIANCE_OPTION,
    SS_TYPE,
    TABLE_ARGUMENT,
    bundle,
    dispatch,
)
from ruddy.cli.commands import (
    run_factorial,
    run_manova,
    run_marginal_means,
    run_mixed_effects,
    run_permanova,
)

app = typer.Typer(
    name="model",
    no_args_is_help=True,
    context_settings=CONTEXT_SETTINGS,
    help="Fit explicit factorial, marginal, mixed-effects and multivariate models.",
)


@app.command("factorial", context_settings=CONTEXT_SETTINGS)
def factorial(
    input: str = TABLE_ARGUMENT,
    id_column: str | None = ID_COLUMN,
    response: list[str] = RESPONSE,
    factor: list[str] = FACTOR,
    covariate: list[str] = COVARIATE,
    annotation: list[str] = ANNOTATION,
    exclude: list[str] = EXCLUDE,
    numeric: list[str] = NUMERIC,
    categorical: list[str] = CATEGORICAL,
    min_numeric_n: int = MIN_NUMERIC_N,
    max_category_levels: int = MAX_CATEGORY_LEVELS,
    max_missingness_patterns: int = MAX_MISSINGNESS_PATTERNS,
    max_pairwise_columns: int = MAX_PAIRWISE_COLUMNS,
    output_dir: str | None = OUTPUT_DIR,
    formula: str | None = FORMULA,
    interaction: list[str] = INTERACTION,
    ss_type: SSType = SS_TYPE,
    p_adjust: PAdjust = P_ADJUST_NONE,
    robust_covariance: RobustCovariance = ROBUST_COVARIANCE_OPTION,
    min_cell_n: int = MIN_CELL_N,
    max_factor_levels: int = MAX_FACTOR_LEVELS,
    max_design_cells: int = MAX_DESIGN_CELLS,
    max_design_columns: int = MAX_DESIGN_COLUMNS,
    max_interaction_order: int = MAX_INTERACTION_ORDER,
    diagnostic_alpha: float = DIAGNOSTIC_ALPHA,
    condition_number_threshold: float = CONDITION_NUMBER_THRESHOLD,
) -> None:
    """Run explicit factorial ANOVA/ANCOVA with interactions and diagnostics."""
    dispatch(run_factorial, bundle(locals()), command="model factorial")


@app.command("marginal-means", context_settings=CONTEXT_SETTINGS)
def marginal_means(
    input: str = TABLE_ARGUMENT,
    id_column: str | None = ID_COLUMN,
    response: list[str] = RESPONSE,
    factor: list[str] = FACTOR,
    covariate: list[str] = COVARIATE,
    annotation: list[str] = ANNOTATION,
    exclude: list[str] = EXCLUDE,
    numeric: list[str] = NUMERIC,
    categorical: list[str] = CATEGORICAL,
    min_numeric_n: int = MIN_NUMERIC_N,
    max_category_levels: int = MAX_CATEGORY_LEVELS,
    max_missingness_patterns: int = MAX_MISSINGNESS_PATTERNS,
    max_pairwise_columns: int = MAX_PAIRWISE_COLUMNS,
    output_dir: str | None = OUTPUT_DIR,
    marginal_response: str | None = MARGINAL_RESPONSE,
    marginal_factor: list[str] = MARGINAL_FACTOR,
    marginal_covariate: list[str] = MARGINAL_COVARIATE,
    marginal_interaction: list[str] = MARGINAL_INTERACTION,
    marginal_formula: str | None = MARGINAL_FORMULA,
    marginal_term: list[str] = MARGINAL_TERM,
    marginal_p_adjust: PAdjust = MARGINAL_P_ADJUST,
    max_interaction_order: int = MAX_INTERACTION_ORDER,
    random_state: int = RANDOM_STATE,
    max_shapiro_n: int = MAX_SHAPIRO_N,
    partial_covariate: list[str] = PARTIAL_COVARIATE,
    dependence_min_pairs: int = DEPENDENCE_MIN_PAIRS,
    dependence_max_columns: int = DEPENDENCE_MAX_COLUMNS,
    dependence_permutations: int = DEPENDENCE_PERMUTATIONS,
    mi_neighbors: int = MI_NEIGHBORS,
    confidence_level: float = CONFIDENCE_LEVEL,
    interval_correlation: list[CorrelationMethod] = INTERVAL_CORRELATION,
    bootstrap_resamples: int = BOOTSTRAP_RESAMPLES,
    bootstrap_method: BootstrapMethod = BOOTSTRAP_METHOD,
) -> None:
    """Estimate marginal means and pairwise model contrasts."""
    dispatch(run_marginal_means, bundle(locals()), command="model marginal-means")


@app.command("mixed-effects", context_settings=CONTEXT_SETTINGS)
def mixed_effects(
    input: str = TABLE_ARGUMENT,
    id_column: str | None = ID_COLUMN,
    response: list[str] = RESPONSE,
    factor: list[str] = FACTOR,
    covariate: list[str] = COVARIATE,
    annotation: list[str] = ANNOTATION,
    exclude: list[str] = EXCLUDE,
    numeric: list[str] = NUMERIC,
    categorical: list[str] = CATEGORICAL,
    min_numeric_n: int = MIN_NUMERIC_N,
    max_category_levels: int = MAX_CATEGORY_LEVELS,
    max_missingness_patterns: int = MAX_MISSINGNESS_PATTERNS,
    max_pairwise_columns: int = MAX_PAIRWISE_COLUMNS,
    output_dir: str | None = OUTPUT_DIR,
    mixed_group: str = MIXED_GROUP_REQUIRED,
    mixed_response: str | None = MIXED_RESPONSE,
    mixed_factor: list[str] = MIXED_FACTOR,
    mixed_covariate: list[str] = MIXED_COVARIATE,
    mixed_interaction: list[str] = MIXED_INTERACTION,
    mixed_formula: str | None = MIXED_FORMULA,
    mixed_random_slope: list[str] = MIXED_RANDOM_SLOPE,
    mixed_ml: bool = MIXED_ML,
    mixed_optimizer: str = MIXED_OPTIMIZER,
    mixed_max_iter: int = MIXED_MAX_ITER,
    mixed_min_groups: int = MIXED_MIN_GROUPS,
    mixed_min_group_n: int = MIXED_MIN_GROUP_N,
    max_interaction_order: int = MAX_INTERACTION_ORDER,
    random_state: int = RANDOM_STATE,
    max_shapiro_n: int = MAX_SHAPIRO_N,
    partial_covariate: list[str] = PARTIAL_COVARIATE,
    dependence_min_pairs: int = DEPENDENCE_MIN_PAIRS,
    dependence_max_columns: int = DEPENDENCE_MAX_COLUMNS,
    dependence_permutations: int = DEPENDENCE_PERMUTATIONS,
    mi_neighbors: int = MI_NEIGHBORS,
    confidence_level: float = CONFIDENCE_LEVEL,
    interval_correlation: list[CorrelationMethod] = INTERVAL_CORRELATION,
    bootstrap_resamples: int = BOOTSTRAP_RESAMPLES,
    bootstrap_method: BootstrapMethod = BOOTSTRAP_METHOD,
) -> None:
    """Fit a random-intercept model with optional numeric random slopes."""
    dispatch(run_mixed_effects, bundle(locals()), command="model mixed-effects")


@app.command("manova", context_settings=CONTEXT_SETTINGS)
def manova(
    input: str = TABLE_ARGUMENT,
    id_column: str | None = ID_COLUMN,
    response: list[str] = RESPONSE,
    factor: list[str] = FACTOR,
    covariate: list[str] = COVARIATE,
    annotation: list[str] = ANNOTATION,
    exclude: list[str] = EXCLUDE,
    numeric: list[str] = NUMERIC,
    categorical: list[str] = CATEGORICAL,
    min_numeric_n: int = MIN_NUMERIC_N,
    max_category_levels: int = MAX_CATEGORY_LEVELS,
    max_missingness_patterns: int = MAX_MISSINGNESS_PATTERNS,
    max_pairwise_columns: int = MAX_PAIRWISE_COLUMNS,
    output_dir: str | None = OUTPUT_DIR,
    max_responses: int = MAX_RESPONSES,
    max_factor_levels: int = MAX_FACTOR_LEVELS,
    min_level_n: int = MIN_LEVEL_N,
) -> None:
    """Run low/moderate-dimensional main-effects MANOVA on a tabular dataset."""
    dispatch(run_manova, bundle(locals()), command="model manova")


@app.command("permanova", context_settings=CONTEXT_SETTINGS)
def permanova(
    input: str = TABLE_ARGUMENT,
    id_column: str | None = ID_COLUMN,
    response: list[str] = RESPONSE,
    factor: list[str] = FACTOR,
    covariate: list[str] = COVARIATE,
    annotation: list[str] = ANNOTATION,
    exclude: list[str] = EXCLUDE,
    numeric: list[str] = NUMERIC,
    categorical: list[str] = CATEGORICAL,
    min_numeric_n: int = MIN_NUMERIC_N,
    max_category_levels: int = MAX_CATEGORY_LEVELS,
    max_missingness_patterns: int = MAX_MISSINGNESS_PATTERNS,
    max_pairwise_columns: int = MAX_PAIRWISE_COLUMNS,
    output_dir: str | None = OUTPUT_DIR,
    group: list[str] = GROUP,
    feature_input: str | None = FEATURE_INPUT,
    feature_id_column: str | None = FEATURE_ID_COLUMN,
    feature_ids_file: str | None = FEATURE_IDS_FILE,
    feature_column: list[str] = FEATURE_COLUMN,
    feature_alignment: Alignment = FEATURE_ALIGNMENT,
    permanova_factor: str | None = PERMANOVA_FACTOR,
    permanova_metric: str = PERMANOVA_METRIC,
    permanova_permutations: int = PERMANOVA_PERMUTATIONS,
    permanova_min_group_n: int = PERMANOVA_MIN_GROUP_N,
    permanova_max_group_levels: int = PERMANOVA_MAX_GROUP_LEVELS,
    random_state: int = RANDOM_STATE,
) -> None:
    """Run PERMANOVA and PERMDISP on a feature space."""
    dispatch(run_permanova, bundle(locals()), command="model permanova")
