"""``ruddy pipeline`` — the unified, explicitly configured analysis run."""

from __future__ import annotations

from ruddy.cli._enums import (
    Alignment,
    AnalysisBlock,
    AnomalyMethod,
    BootstrapMethod,
    ComparisonTest,
    CompositionalTransform,
    CorrelationMethod,
    OutlierMethod,
    PAdjust,
    PosthocMethod,
    RobustCovariance,
    Scaling,
    SimilarityMethod,
    SSType,
)
from ruddy.cli._options import (
    ALR_DENOMINATOR,
    ANNOTATION,
    ANOMALY_METHOD,
    ANOMALY_SCALING,
    BAYESIAN_CREDIBLE_LEVEL,
    BAYESIAN_DRAWS,
    BAYESIAN_GROUP,
    BAYESIAN_MIN_N,
    BAYESIAN_ROPE_HIGH,
    BAYESIAN_ROPE_LOW,
    BAYESIAN_VARIABLE,
    BOOTSTRAP_METHOD,
    BOOTSTRAP_RESAMPLES,
    CATEGORICAL,
    CCA_COMPONENTS,
    CCA_MAX_ITER,
    CCA_SCALING,
    CCA_TOL,
    COMPARISON_FEATURE_COLUMN,
    COMPARISON_FEATURE_ID_COLUMN,
    COMPARISON_FEATURE_IDS_FILE,
    COMPARISON_FEATURE_INPUT,
    COMPARISON_TEST,
    COMPOSITIONAL_TRANSFORM,
    CONDITION_NUMBER_THRESHOLD,
    CONFIDENCE_LEVEL,
    CONTAMINATION,
    CORRELATION,
    COVARIATE,
    DEPENDENCE_MAX_COLUMNS,
    DEPENDENCE_MIN_PAIRS,
    DEPENDENCE_PERMUTATIONS,
    DIAGNOSTIC_ALPHA,
    DISTANCE_METRIC,
    DISTANCE_SIMILARITY_METHOD,
    ENABLE,
    EXCLUDE,
    FACTOR,
    FACTORIAL_FORMULA,
    FACTORIAL_P_ADJUST,
    FACTORIAL_RESPONSE,
    FEATURE_ALIGNMENT,
    FEATURE_COLUMN,
    FEATURE_ID_COLUMN,
    FEATURE_IDS_FILE,
    FEATURE_INPUT,
    GROUP,
    ID_COLUMN,
    INCLUDE_FLAGS,
    INTERACTION,
    INTERVAL_CORRELATION,
    IQR_MULTIPLIER,
    ISOLATION_ESTIMATORS,
    LOF_NEIGHBORS,
    MAHALANOBIS_QUANTILE,
    MANOVA_MAX_FACTOR_LEVELS,
    MANOVA_MAX_RESPONSES,
    MANOVA_MIN_LEVEL_N,
    MANTEL_PERMUTATIONS,
    MARGINAL_COVARIATE,
    MARGINAL_FACTOR,
    MARGINAL_FORMULA,
    MARGINAL_INTERACTION,
    MARGINAL_P_ADJUST,
    MARGINAL_RESPONSE,
    MARGINAL_TERM,
    MAX_CATEGORY_LEVELS,
    MAX_COLLINEARITY_FEATURES,
    MAX_CORRELATION_COLUMNS,
    MAX_COVARIANCE_FEATURES,
    MAX_DESIGN_CELLS,
    MAX_DESIGN_COLUMNS,
    MAX_FACTOR_LEVELS,
    MAX_GROUP_LEVELS,
    MAX_INTERACTION_ORDER,
    MAX_MAHALANOBIS_FEATURES,
    MAX_MISSINGNESS_PATTERNS,
    MAX_PAIRWISE_COLUMNS,
    MAX_SHAPIRO_N,
    MI_NEIGHBORS,
    MIN_CELL_N,
    MIN_CORRELATION_PAIRS,
    MIN_GROUP_N,
    MIN_NUMERIC_N,
    MIXED_COVARIATE,
    MIXED_FACTOR,
    MIXED_FORMULA,
    MIXED_GROUP,
    MIXED_INTERACTION,
    MIXED_MAX_ITER,
    MIXED_MIN_GROUP_N,
    MIXED_MIN_GROUPS,
    MIXED_ML,
    MIXED_OPTIMIZER,
    MIXED_RANDOM_SLOPE,
    MIXED_RESPONSE,
    MULTIVARIATE_SCALING,
    NO_ROBUST_MAHALANOBIS,
    NO_SPEARMAN,
    NUMERIC,
    OUTLIER_METHOD,
    OUTPUT_DIR,
    P_ADJUST,
    PAIRWISE,
    PARTIAL_COVARIATE,
    PERMANOVA_FACTOR,
    PERMANOVA_MAX_GROUP_LEVELS,
    PERMANOVA_METRIC,
    PERMANOVA_MIN_GROUP_N,
    PERMANOVA_PERMUTATIONS,
    POSTHOC_FACTOR,
    POSTHOC_METHOD,
    POSTHOC_RESPONSE,
    PROJECTION_METRIC,
    PROJECTION_N_COMPONENTS,
    PROJECTION_SCALING,
    RANDOM_STATE,
    REPLACE_ZEROS,
    REPRESENTATION_ALIGNMENT,
    RESPONSE,
    ROBUST_COVARIANCE_OPTION,
    ROBUST_SUPPORT_FRACTION,
    ROBUST_Z_THRESHOLD,
    SS_TYPE,
    TABLE_ARGUMENT,
    TSNE_MAX_ITER,
    TSNE_PERPLEXITY,
    UMAP_MIN_DIST,
    UMAP_N_NEIGHBORS,
    ZERO_REPLACEMENT_FRACTION,
    bundle,
    dispatch,
)
from ruddy.cli.commands import run_analyze


def pipeline(
    input: str = TABLE_ARGUMENT,
    id_column: str | None = ID_COLUMN,
    response: list[str] = RESPONSE,
    factor: list[str] = FACTOR,
    covariate: list[str] = COVARIATE,
    annotation: list[str] = ANNOTATION,
    exclude: list[str] = EXCLUDE,
    numeric: list[str] = NUMERIC,
    categorical: list[str] = CATEGORICAL,
    min_numeric_n: int = MIN_NUMERIC_N,
    max_category_levels: int = MAX_CATEGORY_LEVELS,
    max_missingness_patterns: int = MAX_MISSINGNESS_PATTERNS,
    max_pairwise_columns: int = MAX_PAIRWISE_COLUMNS,
    output_dir: str | None = OUTPUT_DIR,
    random_state: int = RANDOM_STATE,
    max_shapiro_n: int = MAX_SHAPIRO_N,
    partial_covariate: list[str] = PARTIAL_COVARIATE,
    dependence_min_pairs: int = DEPENDENCE_MIN_PAIRS,
    dependence_max_columns: int = DEPENDENCE_MAX_COLUMNS,
    dependence_permutations: int = DEPENDENCE_PERMUTATIONS,
    mi_neighbors: int = MI_NEIGHBORS,
    confidence_level: float = CONFIDENCE_LEVEL,
    interval_correlation: list[CorrelationMethod] = INTERVAL_CORRELATION,
    bootstrap_resamples: int = BOOTSTRAP_RESAMPLES,
    bootstrap_method: BootstrapMethod = BOOTSTRAP_METHOD,
    enable: list[AnalysisBlock] = ENABLE,
    group: list[str] = GROUP,
    correlation: list[CorrelationMethod] = CORRELATION,
    comparison_test: list[ComparisonTest] = COMPARISON_TEST,
    p_adjust: PAdjust = P_ADJUST,
    min_group_n: int = MIN_GROUP_N,
    min_correlation_pairs: int = MIN_CORRELATION_PAIRS,
    max_group_levels: int = MAX_GROUP_LEVELS,
    max_correlation_columns: int = MAX_CORRELATION_COLUMNS,
    pairwise: bool = PAIRWISE,
    outlier_method: list[OutlierMethod] = OUTLIER_METHOD,
    iqr_multiplier: float = IQR_MULTIPLIER,
    robust_z_threshold: float = ROBUST_Z_THRESHOLD,
    include_flags: bool = INCLUDE_FLAGS,
    feature_input: str | None = FEATURE_INPUT,
    feature_id_column: str | None = FEATURE_ID_COLUMN,
    feature_ids_file: str | None = FEATURE_IDS_FILE,
    feature_column: list[str] = FEATURE_COLUMN,
    feature_alignment: Alignment = FEATURE_ALIGNMENT,
    projection_n_components: int = PROJECTION_N_COMPONENTS,
    projection_scaling: Scaling = PROJECTION_SCALING,
    projection_metric: str = PROJECTION_METRIC,
    tsne_perplexity: float = TSNE_PERPLEXITY,
    tsne_max_iter: int = TSNE_MAX_ITER,
    umap_n_neighbors: int = UMAP_N_NEIGHBORS,
    umap_min_dist: float = UMAP_MIN_DIST,
    multivariate_scaling: Scaling = MULTIVARIATE_SCALING,
    no_spearman: bool = NO_SPEARMAN,
    no_robust_mahalanobis: bool = NO_ROBUST_MAHALANOBIS,
    mahalanobis_quantile: float = MAHALANOBIS_QUANTILE,
    robust_support_fraction: float | None = ROBUST_SUPPORT_FRACTION,
    max_covariance_features: int = MAX_COVARIANCE_FEATURES,
    max_collinearity_features: int = MAX_COLLINEARITY_FEATURES,
    max_mahalanobis_features: int = MAX_MAHALANOBIS_FEATURES,
    manova_max_responses: int = MANOVA_MAX_RESPONSES,
    manova_max_factor_levels: int = MANOVA_MAX_FACTOR_LEVELS,
    manova_min_level_n: int = MANOVA_MIN_LEVEL_N,
    factorial_response: str | None = FACTORIAL_RESPONSE,
    factorial_formula: str | None = FACTORIAL_FORMULA,
    interaction: list[str] = INTERACTION,
    ss_type: SSType = SS_TYPE,
    factorial_p_adjust: PAdjust = FACTORIAL_P_ADJUST,
    robust_covariance: RobustCovariance = ROBUST_COVARIANCE_OPTION,
    min_cell_n: int = MIN_CELL_N,
    max_factor_levels: int = MAX_FACTOR_LEVELS,
    max_design_cells: int = MAX_DESIGN_CELLS,
    max_design_columns: int = MAX_DESIGN_COLUMNS,
    max_interaction_order: int = MAX_INTERACTION_ORDER,
    diagnostic_alpha: float = DIAGNOSTIC_ALPHA,
    condition_number_threshold: float = CONDITION_NUMBER_THRESHOLD,
    permanova_factor: str | None = PERMANOVA_FACTOR,
    permanova_metric: str = PERMANOVA_METRIC,
    permanova_permutations: int = PERMANOVA_PERMUTATIONS,
    permanova_min_group_n: int = PERMANOVA_MIN_GROUP_N,
    permanova_max_group_levels: int = PERMANOVA_MAX_GROUP_LEVELS,
    posthoc_response: str | None = POSTHOC_RESPONSE,
    posthoc_factor: str | None = POSTHOC_FACTOR,
    posthoc_method: list[PosthocMethod] = POSTHOC_METHOD,
    marginal_response: str | None = MARGINAL_RESPONSE,
    marginal_factor: list[str] = MARGINAL_FACTOR,
    marginal_covariate: list[str] = MARGINAL_COVARIATE,
    marginal_interaction: list[str] = MARGINAL_INTERACTION,
    marginal_formula: str | None = MARGINAL_FORMULA,
    marginal_term: list[str] = MARGINAL_TERM,
    marginal_p_adjust: PAdjust = MARGINAL_P_ADJUST,
    mixed_group: str | None = MIXED_GROUP,
    mixed_response: str | None = MIXED_RESPONSE,
    mixed_factor: list[str] = MIXED_FACTOR,
    mixed_covariate: list[str] = MIXED_COVARIATE,
    mixed_interaction: list[str] = MIXED_INTERACTION,
    mixed_formula: str | None = MIXED_FORMULA,
    mixed_random_slope: list[str] = MIXED_RANDOM_SLOPE,
    mixed_ml: bool = MIXED_ML,
    mixed_optimizer: str = MIXED_OPTIMIZER,
    mixed_max_iter: int = MIXED_MAX_ITER,
    mixed_min_groups: int = MIXED_MIN_GROUPS,
    mixed_min_group_n: int = MIXED_MIN_GROUP_N,
    comparison_feature_input: str | None = COMPARISON_FEATURE_INPUT,
    comparison_feature_id_column: str | None = COMPARISON_FEATURE_ID_COLUMN,
    comparison_feature_ids_file: str | None = COMPARISON_FEATURE_IDS_FILE,
    comparison_feature_column: list[str] = COMPARISON_FEATURE_COLUMN,
    representation_alignment: Alignment = REPRESENTATION_ALIGNMENT,
    cca_components: int = CCA_COMPONENTS,
    cca_scaling: Scaling = CCA_SCALING,
    cca_max_iter: int = CCA_MAX_ITER,
    cca_tol: float = CCA_TOL,
    distance_metric: str = DISTANCE_METRIC,
    distance_similarity_method: SimilarityMethod = DISTANCE_SIMILARITY_METHOD,
    mantel_permutations: int = MANTEL_PERMUTATIONS,
    compositional_transform: CompositionalTransform = COMPOSITIONAL_TRANSFORM,
    replace_zeros: bool = REPLACE_ZEROS,
    zero_replacement_fraction: float = ZERO_REPLACEMENT_FRACTION,
    alr_denominator: int = ALR_DENOMINATOR,
    bayesian_variable: list[str] = BAYESIAN_VARIABLE,
    bayesian_group: list[str] = BAYESIAN_GROUP,
    bayesian_credible_level: float = BAYESIAN_CREDIBLE_LEVEL,
    bayesian_rope_low: float = BAYESIAN_ROPE_LOW,
    bayesian_rope_high: float = BAYESIAN_ROPE_HIGH,
    bayesian_draws: int = BAYESIAN_DRAWS,
    bayesian_min_n: int = BAYESIAN_MIN_N,
    anomaly_method: list[AnomalyMethod] = ANOMALY_METHOD,
    anomaly_scaling: Scaling = ANOMALY_SCALING,
    contamination: str = CONTAMINATION,
    isolation_estimators: int = ISOLATION_ESTIMATORS,
    lof_neighbors: int = LOF_NEIGHBORS,
) -> None:
    """Run an explicitly configured unified Ruddy analysis pipeline."""
    dispatch(run_analyze, bundle(locals()), command="pipeline", legacy="analyze")
