"""Shared contracts, enumerations, and exceptions."""

from ruddy.core.enums import (
    AdvisoryLevel,
    AlignmentMode,
    AnalysisBlock,
    AnnotationCoverage,
    ColumnKind,
    ColumnRole,
    ComparisonTest,
    CorrelationMethod,
    OutlierMethod,
    PAdjustMethod,
    ProjectionMethod,
    ResultStatus,
    ScalingMethod,
)
from ruddy.core.exceptions import (
    AlignmentError,
    ContractError,
    DataValidationError,
    DuplicateObservationIDError,
    FeatureMatrixValidationError,
    KindConflictError,
    MissingObservationIDError,
    OptionalDependencyError,
    ResultContractError,
    RoleConflictError,
    RuddyError,
    RuddyIOError,
    UnknownColumnError,
)

__all__ = [
    "AdvisoryLevel",
    "AnalysisBlock",
    "AnnotationCoverage",
    "AlignmentError",
    "AlignmentMode",
    "ColumnKind",
    "ColumnRole",
    "ComparisonTest",
    "CorrelationMethod",
    "ContractError",
    "DataValidationError",
    "DuplicateObservationIDError",
    "FeatureMatrixValidationError",
    "KindConflictError",
    "MissingObservationIDError",
    "OptionalDependencyError",
    "OutlierMethod",
    "ProjectionMethod",
    "ScalingMethod",
    "PAdjustMethod",
    "ResultContractError",
    "ResultStatus",
    "RoleConflictError",
    "RuddyError",
    "RuddyIOError",
    "UnknownColumnError",
]
